#!/bin/bash

birthdate=2001

langcode=YEM

start_time=000000

dir=data/audio/wav

us='_'

combi_letter=$(openssl rand -hex 20 | head -c 10)

speaker_id=$birthdate-$combi_letter

echo "record_id;speaker_id;Utterance_id;10combined_letter;extended_filename;sentence_id;text_id" > preparing.csv

for audio_wav in $dir/*; do

	sentence_id=$(echo $audio_wav | cut -d '.' -f 1 | cut -d '/' -f 4)
	
	base_filename=$(( 10#$sentence_id ))  #base_filename is sentence_id
	
	exfilename=$audio_wav

	record_id="$langcode$us$sentence_id$us$filename$us$speaker_id"
	
	end_time=$(printf "%.0f\n" $(soxi -D $audio_wav))
	
	Utterance_id=$record_id$us$start_time-00000$end_time
	
	echo "$record_id;$speaker_id;$Utterance_id;$combi_letter;$exfilename;$sentence_id;$base_filename"
	echo "$record_id;$speaker_id;$Utterance_id;$combi_letter;$exfilename;$sentence_id;$base_filename" >> preparing.csv
done


#to print all the line of a file without the first line, use:

#echo $record_id;$speaker_id >> preparing.csv	
#echo "$record_id;$speaker_id;$Utterance_id"

